#!/bin/bash
#
# Copyright © 2016-2017 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

REST_URL=${REST_URL:-"http://localhost:8080"}
MQTT_URLS=${MQTT_URLS:-"tcp://localhost:1883"}
DEVICE_COUNT=${DEVICE_COUNT:-"20000"}
PUBLISH_TELEMETRY_COUNT=${PUBLISH_TELEMETRY_COUNT:-"60"}
PUBLISH_TELEMETRY_PAUSE=${PUBLISH_TELEMETRY_PAUSE:-"1000"}
USERNAME=${USERNAME:-"tenant@thingsboard.org"}
PASSWORD=${PASSWORD:-"tenant"}

TEST_PROJECT_DIR="/root/performance-tests"
TEST_PROJECT_CONFIG_FILE="$TEST_PROJECT_DIR/src/main/resources/test.properties"

function install_dependencies() {
    mvn install:install-file -Dfile=/root/tb-gatling-1.0.0.jar -DgroupId=org.thingsboard -DartifactId=gatling-mqtt -Dversion=1.0.0 -Dpackaging=jar
    mvn install:install-file -Dfile=/root/tools-1.2.3.jar -DgroupId=org.thingsboard -DartifactId=tools -Dversion=1.2.3 -Dpackaging=jar
    mvn install:install-file -Dfile=/root/data-1.2.3.jar -DgroupId=org.thingsboard.common -DartifactId=data -Dversion=1.2.3 -Dpackaging=jar
}

function install_project() {
    tar -zxvf /root/project-src.tar.gz -C $TEST_PROJECT_DIR
}

function create_config() {
	rm -f $TEST_PROJECT_CONFIG_FILE
    echo "Creating performance test configuration"
    echo "#This file was autogenerated by tb test project DO NOT EDIT" >> $TEST_PROJECT_CONFIG_FILE
	echo "restUrl=$REST_URL" >> $TEST_PROJECT_CONFIG_FILE
    echo "mqttUrls=$MQTT_URLS" >> $TEST_PROJECT_CONFIG_FILE
    echo "deviceCount=$DEVICE_COUNT" >> $TEST_PROJECT_CONFIG_FILE
    echo "publishTelemetryCount=$PUBLISH_TELEMETRY_COUNT" >> $TEST_PROJECT_CONFIG_FILE
    echo "publishTelemetryPause=$PUBLISH_TELEMETRY_PAUSE" >> $TEST_PROJECT_CONFIG_FILE
    echo "username=USERNAME" >> $TEST_PROJECT_CONFIG_FILE
    echo "password=$PASSWORD" >> $TEST_PROJECT_CONFIG_FILE
    echo "Wrote performance test configuration file to $TEST_PROJECT_CONFIG_FILE"
}

function run_project() {
    cd $TEST_PROJECT_DIR
    mvn clean install -Dmaven.exec.skip=true gatling:execute
}

install_dependencies && install_project && create_config && run_project