#!/bin/sh

mkdir -m 0755 -p ${pkg.logFolder}
chown -R ${pkg.name}: ${pkg.logFolder}
chown -R ${pkg.name}: ${pkg.installFolder}

if [ $1 -eq 1 ] ; then
        # Initial installation
        systemctl --no-reload enable ${pkg.name}.service >/dev/null 2>&1 || :
fi
